# Generated by Django 4.1.1 on 2022-09-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=254, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'stadium',
                'verbose_name_plural': 'stadiums',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='stadium.stadium', verbose_name='stadium')),
            ],
            options={
                'verbose_name': 'seat',
                'verbose_name_plural': 'seats',
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('stadium', 'code'), name='unique_seat_stadium_code'),
        ),
    ]
