# Generated by Django 4.1.1 on 2022-09-10 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmatches', to='team.team', verbose_name='guest team')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmatches', to='team.team', verbose_name='host team')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='MatchSeatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='price')),
                ('is_reserved', models.BooleanField(default=False, help_text='Designates whether the seat is reserved or not.', verbose_name='reserved status')),
                ('is_paid', models.BooleanField(default=False, help_text='Designates whether the seat is bought or not. ', verbose_name='paid')),
                ('date_reserved', models.DateTimeField(blank=True, null=True, verbose_name='date reserved')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_seats', to=settings.AUTH_USER_MODEL, verbose_name='buyer')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_seats_info', to='match.match', verbose_name='match')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_seats_info', to='stadium.seat', verbose_name='seat')),
            ],
            options={
                'verbose_name': 'match seat info',
                'verbose_name_plural': 'match seats info',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='seats',
            field=models.ManyToManyField(related_name='matches', through='match.MatchSeatInfo', to='stadium.seat', verbose_name='seats'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='stadium.stadium', verbose_name='stadium'),
        ),
        migrations.AddConstraint(
            model_name='matchseatinfo',
            constraint=models.UniqueConstraint(fields=('match', 'seat'), name='unique_info_match_seat'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('stadium', 'datetime'), name='unique_match_stadium_datetime'),
        ),
    ]
